### PR TITLE
fixing footer issues and refreshing header bar issue

### PR DESCRIPTION
**Pull request by rossneilson**
## Description

There were some remaining issues with the footer bar so I have fixed this again for all pages.
Also @martinkrung previously mentioned that the header was being re-rendered when navigating pages so I have moved the component up to the root level so it is always rendered and doesn't get re-rendered.

## Motivation and Context
#256

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by martinkrung — CHANGES_REQUESTED** [review]
I don't think this is what we need for the footer, now the footer is not visible on first sight and we have a scrollbar. I think if people do not see the footer they don't see there is more info.

Or is this because there is no sale?


Screenshot at 2021-06-15 14-53-17

**Comment by rossneilson** [comment]
> I don't think this is what we need for the footer, now the footer is not visible on first sight and we have a scrollbar. I think if people do not see the footer they don't see there is more info.
> 
> Or is this because there is no sale?

Hm, I'll look at this again and make it better

**Comment by rossneilson** [comment]
Ok, finally fixed footer for all pages (fingers crossed). Issue was due to lack of control over root container size and properties

**Review by martinkrung — APPROVED** [review]

**Review by hhamud — COMMENTED** [review]
LGTM!

**Pull request merged**
