### PR TITLE
Changed input to take xdai and calculate quantity

### PR DESCRIPTION
**Pull request by rossneilson**
## Description

Changed logic for calculating value since value is being decided by user.
Instead, it calculated quantity and then checks for errors against both.
Also using a better method (simpler) to do fractional calculations.

Added green text to show quantity of tokens to be received and red text for errors.

FIxed margins on linked button.
Added disable prop for buttons to stop purchases with active error in form.

## Motivation and Context
#241

## How Has This Been Tested?
Locally buying whole token amount and fractional amounts and testing maths for calculating quantity for different dollar values. Also purchased token to test correct amount of wxdai was removed from wallet.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by martinkrung — CHANGES_REQUESTED** [review]
I was thinking this is a bug, but in fact the logic is right. Its confusing that I fill 5 in to the form and then the answer is that its over 5.5.

Screenshot at 2021-06-11 09-46-33



So change to this simpler and I think less confusing massage.

Quite often see is that 2.75 is a link, and if you click on it, then it sets the value in the form.

Screenshot at 2021-06-11 10-05-02


I had a much wordier variant, but simplicity wins:

Screenshot at 2021-06-11 10-04-10

**Comment by rossneilson** [comment]
> I was thinking this is a bug, but in fact the logic is right. Its confusing that I fill 5 in to the form and then the answer is that its over 5.5.
> 
> Screenshot at 2021-06-11 09-46-33
> 
> So change to this simpler and I think less confusing massage.
> 
> Quite often see is that 2.75 is a link, and if you click on it, then it sets the value in the form.
> 
> Screenshot at 2021-06-11 10-05-02
> 
> I had a much wordier variant, but simplicity wins:
> 
> Screenshot at 2021-06-11 10-04-10

Good catch, I forgot about that. Will change shortly

**Comment by martinkrung** [comment]
I just added some more about "you'll" above, I just write this here, that you don't miss.

**Comment by rossneilson** [comment]
I have pushed those changes now.
I think personally "You get X tokens" looks the best, but I can change it if something else works better.
I have left out the clickable error message to set to max/min since this is a bit more complicated. I can make a separate issue for it if you think it should be added.

**Comment by martinkrung** [comment]
Thanks, works fine.

Can you make a ticket for the click to set max in the interface? Please set it to "next version" in milestone.

**Comment by rossneilson** [comment]
Done: #244

**Pull request merged**
