### PR TITLE
Add Max button to token purchase form.

### LINKED ISSUE #244: Set max button in purchase form
A button should be available in the fixed price sale form to allow users to set the max number of tokens available to purchase.
This should either be a button that is always visible beside the input or a clickable link in the error message that appears when an input amount is over the max allocation limit.

### PR DESCRIPTION
**Pull request by mprasanjith**
## Description

- Add Max button to the token purchase form.
- The max value is either the wallet token balance or the maximum purchase amount. (Whichever is lower)
- Refactor purchase value validations to be reusable.

## Motivation and Context

Fixes #244.

## How Has This Been Tested?

Tested locally using start-xdai.

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hhamud — CHANGES_REQUESTED** [review]
There's a  UI problem when you do use the max button. 
image

**Comment by mprasanjith** [comment]
> 
> 
> There's a UI problem when you do use the max button.
> image

Ah, it's the JS rounding issue @rossneilson ran into earlier. Used to same `fixRounding` function to fix this one as well.

**Review by hhamud — APPROVED** [review]

**Comment by rossneilson** [comment]
Not a huge issue, but the above visual glitch still happens if the user wants to buy an insane amount of tokens.
I know this is an edge case but probably worth fixing.
A super simple fix would just be setting the background colour of the button to the same as the input so the large numbers simply go underneath the button.

**Review by rossneilson — APPROVED** [review]

**Comment by mprasanjith** [comment]
For now I added a background color for the overlay, but in the future we should change it so that the button and the token name are not overlaid on the input field.

**Pull request merged**
