### PR TITLE
SC 0.1.1 integration

### PR DESCRIPTION
**Pull request by rossneilson**
### Done
- Changes all denominations to tokenIn
- Updates contracts and all references to variables and methods in them
- Update to 0.1.1 subgraph release
- Bids showing in sale view
- Proper claiming of tokens

For future the manual copying of abis can be done automatically and used from mesa-js sdk instead of in the UI codebase

1. For now all that was done was copying ABIs form smart contract build.
2. Then run `npm run typechain` to generate new contract ts files.

## Motivation and Context
#290 
#327 
#335

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rossneilson** [comment]
Bids are not currently showing up in the table component, but data appears fine in console logs
Since @hhamud implemented this it may be best for you to fix it here.

Manually change subgraph endpoint in node modules until 0.1.3 working (currently a type issue)
mesa-interface/node_modules/@dxdao/mesa/dist/index.js -> XDAI_CONFIG.subgraph -> ".../aqua-xdai-next"

Once bids show up the rest of claiming/withdrawing can be tested.
Once stable this can be merged

**Comment by hhamud** [comment]
> Bids are not currently showing up in the table component, but data appears fine in console logs
> Since @hhamud implemented this it may be best for you to fix it here.
> 
> Manually change subgraph endpoint in node modules until 0.1.3 working (currently a type issue)
> mesa-interface/node_modules/@dxdao/mesa/dist/index.js -> XDAI_CONFIG.subgraph -> ".../aqua-xdai-next"
> 
> Once bids show up the rest of claiming/withdrawing can be tested.
> Once stable this can be merged

Fixed the table issue in this [PR](#339)

**Comment by rossneilson** [comment]
I have tested everything locally and everything seems to be working as expected. 
It should be reviewed, however merging will need to wait until mesa-js 0.1.3 is ready.
For instructions to run locally see PR description.
I will raise issues for a few bugs I found.

**Comment by mprasanjith** [comment]
Everything seems to be working fine at a first glance. Flipping tokenIn and tokenOut is great and feels a lot more intuitive.

I got a bunch of error alerts after a purchase. 

image

I don't see any other issues. Great work, as always!

**Review by mprasanjith — CHANGES_REQUESTED** [review]
Everything seems to be working fine at a first glance. Flipping tokenIn and tokenOut is great and feels a lot more intuitive.

I got a bunch of error alerts after a purchase. 

image

I don't see any other issues. Great work, as always!

**Comment by rossneilson** [comment]
> Everything seems to be working fine at a first glance. Flipping tokenIn and tokenOut is great and feels a lot more intuitive.
> 
> I got a bunch of error alerts after a purchase.
> 
> 
> I don't see any other issues. Great work, as always!

Thank you, issue for that here #356

**Review by mprasanjith — APPROVED** [review]
I also had a look again and its the bid update redux call that's failing. Will approve this one.

**Pull request merged**
