### PR TITLE
small ui changes

### PR DESCRIPTION
**Pull request by rossneilson**
## Description
Small UI changes
- Added correct sale token address and link to block explorer
- Removed 'Initial sale'
- Changed 'private' to 'public'
- Added correct max allocation to purchase form

- Below shows different options for making network banner clearer

## Motivation and Context
#232

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rossneilson** [comment]
Here are some options for the network banner from suggestions in the original issue, please give feedback:

スクリーンショット 2021-06-11 10 50 45

スクリーンショット 2021-06-11 10 51 23

**Comment by martinkrung** [comment]
About the buttons color: I think the grey is better.  The white version looks less clickable to me.

In the original ticket, I added this on top, yesterday after some time. I think I should stop doing this and add comments, and not edit. sry.

Screenshot at 2021-06-11 12-20-08

So I would change address to "token address". This is important information. This helps people to check on block-explorer if you invest into the right token or not. in fact it should have more prominent place, but we think about this later.

**Comment by rossneilson** [comment]
> About the buttons color: I think the grey is better. The white version looks less clickable to me.
> 
> In the original ticket, I added this on top, yesterday after some time. I think I should stop doing this and add comments, and not edit. sry.
> 
> Screenshot at 2021-06-11 12-20-08
> 
> So I would change address to "token address". This is important information. This helps people to check on block-explorer if they invest into the right token or not. in fact it should have more prominent place, but we think about this later.
> 
> Maybe rename the one you have done right now to "sale contract address" or just "contract address"?

Thankfully that data is actually very accessible so I have changed the address to represent the actual token address :)

**Review by martinkrung — APPROVED** [review]
Lets go!

**Pull request merged**
